# Generated by Django 6.0 on 2026-01-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="customer_images/"
            ),
        ),
    ]
